### ISSUE TITLE
when trying to build libki-client with QT creator - error "QUrlQuery: No such file of directory"

### ISSUE THREAD

**Issue by woutervanlooy** [Libki/libki-client#1]
in file networkclient.h line 28 gives error

#include <QurlQuery>

error message = QUrlQuery: No such file of directory

**Comment by kylemhall** [comment]
What version of Qt5 are you building against?

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by woutervanlooy** [comment]
Thank you for posting. I did not get your message in my inbox ... but got it working with Qt5 installed on ubuntu distro. First try was on Mint distro, but wont work.

**Comment by kylemhall** [comment]
Glad you got it working!

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )
