### ISSUE TITLE
Client crashes on Windows

### ISSUE THREAD

**Issue by fribeiro-keeps** [Libki/libki-client#100]
Using client v2.2.20.0, the app stops working when reducing the session time for the first time. E.g. The clock starts with 45 minutes and when updates to 44, the client crashes.
I can see the error at Windows Event Viewer but the error details doesn't help much.

I wonder if this is caused by the [date differences](https://github.com/Libki/libki-server/issues/297).

**Comment by kylemhall** [comment]
That certainly sounds possible! Have you checked the client logs? If we are lucky an error might have been logged before it crashed.

**Comment by kylemhall** [comment]
So far I have been unable to reproduce your issue. Can you give me precise steps in order to reproduce it?

**Comment by fribeiro-keeps** [comment]
I've tried to initialize the containers without Timezones variables (LIBKI_TZ and TZ) and all the dates are matching. However, the client still crashes.
Now I installed the latest version v23.05.
The log file is here.
[Log_2023_05_02__11_30_25_247.txt](https://github.com/Libki/libki-client/files/11372250/Log_2023_05_02__11_30_25_247.txt)

Steps to reproduce:
Run the Setup Wizard;
Configure Scheme (http), Host (my server IP), Port (3000);
Specify Location and Client name;
Do not start Libki client automatically;
Nothing (just redisplay the Libki login screen);
Introduce the Password;
Destination Location (C:\Program Files (x86)\Libki);
Click in Install;
Finish;

**Comment by fribeiro-keeps** [comment]
Yes, I see the number changing before it crashes.
Both of those setting are empty.

![Screenshot from 2023-05-02 16-22-33](https://user-images.githubusercontent.com/60617021/235711342-99b78fe1-24ff-40c4-99cf-aee8bad87e7d.png)

**Comment by kylemhall** [comment]
Can you try setting those both to "5" and let me know if it continues to crash?

**Comment by fribeiro-keeps** [comment]
That did the trick :+1:  Libki client doesn't crash with those settings

**Comment by kylemhall** [comment]
excellent! Now I have to find out why the defaults aren't working 😁

**Comment by fribeiro-keeps** [comment]
Thanks for your help! For now I will use this settings :smile:
