### ISSUE TITLE
Send additional network information from the client

### ISSUE THREAD

**Issue by jfmartinezm** [Libki/libki-client#103]
To help support and helpdesk teams, it could be useful if some basic network information could be sent from the client and stored in the server:

- Hostname: To identify clients when the client name is different from the hostname. If there are many clients from different branches and locations, it may not be easy to identify them just by client name.

- IP Address: It could be valuable to have this information to connect to the client for troubleshooting purposes, for example. If dynamic addresses are used, it may not be easy to find out the IP Address.

- MAC Address: Storing this information could make Wake On Lan operations easier: it wouldn't be neccesary to manually specify a list of MAC addresses to wake up, and WOL for individual clients could be implemented more easily.

Implementing that feature on the client would also help with issues #71 and #70. Could use the pointer from the comments in #70 to begin with.

**Comment by jfmartinezm** [comment]
Looks like the code from the link in #70 would still work to get the MAC address, at least with Qt5, although the interfaces and classes used there are deprecated and have been replaced in Qt6. Will have a try to see how it works.

**Comment by jfmartinezm** [comment]
Seems to be working fine, hostname, IP Address and MAC Address are obtained and added to the request on client registration. Will create a PR with the changes.

**Comment by sekjal** [comment]
The associated PR for Libki Server was merged.  Marking this issue resolved.
