### ISSUE TITLE
Problem with configurating libki at work.

### ISSUE THREAD

**Issue by DennisC1996** [Libki/libki-client#105]
Hello, I am struggling to configure a specific setting on Libki. I want to enable a setting that clears the user profile everytime i log off. For example the web-browser history and txt files created on the user account. How do i do this? I do not have access to the libki server, but I do have access to the web based interface with a admin account. Thankful for help. 

Best regards.

/Dennis

**Comment by DennisC1996** [comment]
Thanks for a fast reply Kylemhall. The reason why I made the thread is that I tried using OpenAi's ChatGPT to solve my problem and it came with a solution. I guess it does not work? This is the message it provided.

Locate the libki.conf file. This file is typically located in the Libki installation directory.

Open the libki.conf file using a text editor.

Look for the section titled [Basic] in the libki.conf file. If the section does not exist, you can add it at the end of the file.

Within the [Basic] section, add the following line:



clear_profile_on_logout = true
This configuration option instructs Libki to clear the user profile when a user logs out.

Save the libki.conf file.

Restart the Libki server for the changes to take effect.

After making these configuration changes, when a user logs out of Libki, their profile data will be cleared automatically.

Please note that modifying the libki.conf file requires administrative access to the Libki server. Additionally, it's important to back up the configuration file before making any changes to ensure you can revert to the previous state if needed.

Best regards, Dennis

**Comment by kylemhall** [comment]
Afraid not. ChatGPT is 100% wrong.
