### ISSUE TITLE
Libki Client uploads print job twice

### ISSUE THREAD

**Issue by stop-error** [Libki/libki-client#108]
**Describe the bug**
The Libki Client will sometimes upload a print job twice, with one copy of the print job being invalid.

**To Reproduce**

1. Print a PDF file (in my example test3.pdf) to a printer directory.

2. Libki Client renames the PDF file to "test3.pdf.0.printed". For some reason, the original "test3.pdf" file still exists after the rename operation. There are now two files in the printer directory. "test3.pdf", and "test3.pdf.0.printed"

3. Libki Client uploads "test3.pdf.0.printed" to the server. However, the document appears to be invalid.

4. In the meantime, Libki Client sees the original test3.pdf _again_ and tries to rename it to "test3.pdf.1.printed". This operation fails (maybe it is still locked by the original rename operation?). This part of the issue tends to loop for a bit.

5. Libki Client eventually successfully renames "test3.pdf" and uploads it to the server again. There are now two print jobs list for "test3.pdf" on the server.

**Expected behavior**
Libki client should only upload a print job once.

**Screenshots**
Server UI screenshots attached. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2

**Additional context**
Log file attached.

<img width="1235" alt="server" src="https://github.com/Libki/libki-client/assets/129561633/fb93e62b-e234-4ff7-a100-4bfebc924592">
[Log_2023_08_20__19_42_54_893.txt](https://github.com/Libki/libki-client/files/12390089/Log_2023_08_20__19_42_54_893.txt)

**Comment by kylemhall** [comment]
It sounds like some sort of race condition between the print driver and the client may be the culprit. I can see in your screenshot that the pages column is empty for the invalid PDF. When you get another example of this on your server, can you DM me in the Libki slack workspace?

**Comment by stop-error** [comment]
> It sounds like some sort of race condition between the print driver and the client may be the culprit. I can see in your screenshot that the pages column is empty for the invalid PDF. When you get another example of this on your server, can you DM me in the Libki slack workspace?

Will do!

**Comment by stop-error** [comment]
Just discovered a new issue that may be related. 

I was testing Libki Client's printing with the Libki version of PdfScribe, and it looks like it's uploading the print job before I can specify how many copies to print.

The client might be in need of additional checks to verify the document is ready for upload.

**Comment by kylemhall** [comment]
Considering we can now specify the number of copies to print at release time, I'm wondering if the best path would be for me to find the custom version of PDFScribe we have that doesn't ask for the number of copies ( assuming I still have it or can get it from the group the customized it for us ).

**Comment by kylemhall** [comment]
@stop-error I've updated the client such that it will not attempt to upload any files that are currently being written to by the print driver. Can you test client version 2.2.29 to see if that resolves the issue?

**Comment by stop-error** [comment]
With Microsoft Print to PDF, file size is 0KB as reported by Windows Explorer. I've noticed the size isn't always 0KB, sometimes it grows with the print job. Might be somewhere to start though.

**Comment by kylemhall** [comment]
@stop-error Please try build 2.2.30! 🤞

**Comment by stop-error** [comment]
Seems to be working!
