### ISSUE TITLE
Save Username (Barcode) on Local Machine

### ISSUE THREAD

**Issue by l0chte** [Libki/libki-client#115]
We use Envisionware's LPTOne for print management. When printing, a dialog box opens asking for the patron's barcode number. I would like to create a way to input this (using Auto Hot Key) based on the currently logged in Libki user. Is there a way to save the username to the local computer when logging in?

**Comment by kylemhall** [comment]
You can do this already! In `%APPDATA%/Libki` you will find the file `Libki Kiosk Management System.ini`. When a user is logged in, this file will have the key `LoggedInUser` under the section `session`. I think it should be fairly easy for you to extract the username/cardnumber from this file using AutoHotKey!

**Comment by l0chte** [comment]
Amazing!

**Comment by l0chte** [comment]
Thanks again! 

Using AHK v1: 

`
#SingleInstance Force

DetectHiddenText, on
DetectHiddenWindows, on
SetTitleMatchMode, 3

Sleep, 2000

Loop
{
	WinWait, User Identification, 
	WinActivate
	sleep, 100
  	IniRead, LoggedInUser, %appdata%\Libki\Libki Kiosk Management System.ini, session, LoggedInUser
	; Check if loggedInUser is not empty
	if (LoggedInUser != "")
	{
	Send, %LoggedInUser%
	sendinput, {Enter}
	}
	else
	{
	; If loggedInUser is empty or the key doesn't exist, display an error message
	MsgBox, Unable to retrieve logged in user.
	}
	sleep, 5000
}
`

**Comment by kylemhall** [comment]
@l0chte thanks for sharing you script!
