### ISSUE TITLE
Unable to connect client to server

### ISSUE THREAD

**Issue by hknappe** [Libki/libki-client#122]
**Describe the bug**
All of a sudden all our login attempts ends with the following error:

Error connecting to server. Verify Libki server is accessible from this network. Error Code: 401:Error downloading https://[...]: 443/api/client/v1_0?node=Gjest08&location=hovedbiblioteket&type&action=login&username=[...]&password=**** - server replied: Internal server Error.

This error seem to have come out of "nowhere". Everything worked as expected until suddenly all logins are met with the message over.
The server is up and running and as far as I can see in contact with the clients, because Offline/Online statuses on the clients are shown correctly.

**Comment by kylemhall** [comment]
Have you checked your server logs to see what the error is?

**Comment by hknappe** [comment]
It seem to be related to this:

`10/23/2024 04:00 PM | 380892 | 530db6bee921 | ERROR | Caught exception in Libki::Controller::API::Client::v1_0->index "Not an ARRAY reference at /app/lib/Catalyst/Plugin/LibkiSetting.pm line 234."`

**Comment by kylemhall** [comment]
That relates to the advanced rules. Do you have any advanced rules rules? Do you see the error `Error loading AdvancedRules configuration YAML from system setting` in your logs at all? Have. you tried restarting Libki to clear any internal caches?

**Comment by hknappe** [comment]
Yes, thanks! It was a badly formatted rule there. When we removed it everything worked.
