### ISSUE TITLE
Installer suggestions

### ISSUE THREAD

**Issue by loidor** [Libki/libki-client#19]
Two small things that I think would simplify the installer a little bit:

1. Make http a default value in scheme. My guess is that 99.9% don't change this, and if they do, it's probably to https, so it would be somewhat intuitive to have http as a default value. Of the two, this is the most important since scheme isn't mentioned anywhere in the server installer. 

2. Same thing about port. The server's default port is 3000, so it makes sense to have that as a default value here too.

**Comment by kylemhall** [comment]
I think it would be better to document the wizard installer in the manual. We've started implemented https and using port 80 both via Apache as a reverse proxy to port 3000. It's pretty nice to have the web address be libki.$mylibrary.org with a standard web port.

**Comment by loidor** [comment]
Yeah, that works just as well :)
