### ISSUE TITLE
Libki.ini some functions didn't work

### ISSUE THREAD

**Issue by Shadra** [Libki/libki-client#2]
In the ini file you can set on of there parameters:
; logoutAction defines the action to take when a Libki user logs out of the Libki Client.
;logoutAction=logout           ;Log out of OS
;logoutAction=reboot           ;Reboot computer
logoutAction=no_action       ;Just redisplay the Libki login screen

If you set reboot computer and comment all other things, that I get an error with sudo. But thats a critical security issue, I never can give the libki user sudo rights. If someone try and error to get the password, you are god on this pc. Is there another way to reboot the computer? KDE don't need sudo rights for doing this.

If you set logout and comment all other things, it do nothing. Libki is still running....

The main problem is: how can I terminate and clean up a session?
If I use firefox and other programms, save work here and there and my 30 minutes are ending, I kicked off the programm and another person can logon. All correct. But now it gets dirty, if another user is login in I'm still in the same session as the other user and can access all his/her files and so on. That's a privacy related issue. The work around I see here is a clean restart. At boot I run a shell script that I wrote, which cleans all session data and resett the whole libki user.

So there are multiple issues here:
1. two options didn't work
2. libki has no clean up routine after terminating a user session

What can I do?

**Comment by Shadra** [comment]
nevermind

**Comment by kylemhall** [comment]
On linux, you'll need to give the user running the client sudo rights (
with the no password option ) for just reboot and reboot alone.

As for session cleanup, that's outside the scope of Libki.

There's some open source software called OFRIS that does exactly what your
looking for. Check out the project page here:
http://sourceforge.net/projects/dafturnofris-id/

And for a little help installing check out this link: Is there any Deep
Freeze-like application for Ubuntu?

And here's an alternative solution:
http://www.webupd8.org/2009/07/deep-freeze-like-software-for-ubuntu.html

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )
