### ISSUE TITLE
FYI - Windows 10 Fast Startup

### ISSUE THREAD

**Issue by Fergusonw** [Libki/libki-client#20]
Not sure if this has been reported, but if Fast Startup is enabled on Windows 10 (It is by default), Libki restarts the computer, rather than shutting down.  Pressing the power button or selecting "shut down" from the start menu triggers a reboot (which is instant).

**Comment by loidor** [comment]
I'm 99% sure it's in one of the windows specific script files. Could you please test this for me, so it's easier to localise the bug?

Go to the folder C:\Program Files (x86)\Libki\windows and rename the script files one by one with a reboot and test between each renaming.

**Comment by kylemhall** [comment]
Here's the line where the Windows restart occurs:
https://github.com/Libki/libki-client/blob/master/networkclient.cpp#L547

Basically, the client is calling the command 'shutdown -l -f'

Help me make Great Strides towards a cure for Cystic Fibrosis
<http://fightcf.cff.org/goto/kylehall>
<https://mail.google.com/>
---
http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by loidor** [comment]
Aaaah. Weird though, a logoff shouldn't issue a reboot.

An alternative would be to lock all keys with ahk if shutdown is run from within windows. Not really sure of a nice way to do that though.

**Comment by kylemhall** [comment]
@Fergusonw If you open a command line and issue the command `shutdown  -l -f` can you tell us if the system logs off correctly or reboots?

**Comment by kylemhall** [comment]
@Fergusonw can you also pass us a copy of your ini file? You can usually find it in C:\ProgramData\Libki

**Comment by Fergusonw** [comment]
scheme="http"
[node]
name=Public 3
logoutAction=logout
password=Tusky
onlyStopFor=
location=Tusky
[windows]
EnableStartButton=1

**Comment by kylemhall** [comment]
@Fergusonw Did you try the command `shutdown -l -f` from a command prompt? If so, did it log out of reboot?

**Comment by Fergusonw** [comment]
As an update, I tested out the computers at another branch yesterday, and did not replicate the problem.  I don't have an easy way to get back to the original computers right now, but if I had to take a guess, I would say it's probably an issue with Deep Freeze, rather than Libki.  The computers I worked on yesterday use Reboot Restore and did not have the problem.

**Comment by kylemhall** [comment]
Thanks @Fergusonw 
Let's close this for the time being.
