### ISSUE TITLE
Dev idea: Auto logout inactive users

### ISSUE THREAD

**Issue by loidor** [Libki/libki-client#22]
Haven't looked at all what this would require, but my guess is that it's somewhat of a low hanging fruit. 

We're using the auto prolonging of time if the client isn't reserved. Thing is every now and then users simply leave the client and because of the extended time, it never logs out. New users believe the client is being used but it isn't, and a client can stay open, unused, for quite some time before someone in staff realises it isn't used at all.

**Comment by kylemhall** [comment]
I've been doing some digging and I think this may help us:
https://stackoverflow.com/questions/32040202/qt-5-get-the-mouse-position-in-a-screen

I think we could just capture the mouse coordinates every minute and if
they haven't changed in X minutes ( as defined by a system setting ) we run
the  logout routine! If I find a few minutes I'll test out my idea!

**Comment by loidor** [comment]
Hah, I also looked around and found this: https://stackoverflow.com/questions/3341617/how-to-detect-user-inactivity-in-qt :D  

Guess either would work just fine, as long as the first one is connected to something that reads the keyboard as well.

**Comment by kylemhall** [comment]
The key is we need to detect mouse activity *outside* our application, as it will almost never be the program with focus. That is generally a more challenging feat.

**Comment by TypicalLibrarian** [comment]
If I may suggest another (possible) solution: What if the popup that said 'your time has been extended' rather gave the option to extend the time? As in one button to "Extend by [Time admin sets]" and another to either log off, or simply not extend. If the user doesn't interact, then the computer logs off as usual.

Simply a thought.

**Comment by kylemhall** [comment]
Good thought @TypicalLibrarian, that will *definitely* work if the mouse detection doesn't!
