### ISSUE TITLE
Process manager

### ISSUE THREAD

**Issue by webzi** [Libki/libki-client#23]
Hi,

We are facing some issues.

When users are signed in, they can easily just close the Libki client, by opening the task manager, and then just stop the Libki client - And suddenly they can use the PC for as long as they want.

Are there any way to prevent this? I'm running the latest version of both server and client.

Best regards

Casper.

**Comment by kylemhall** [comment]
You need to disable the Task Manager. Libki itself cannot directly prevent
this as it is too low level a part of Windows, but you should be able to
disable it on all your public computers using the following directions:
https://ccm.net/faq/41738-how-to-prevent-users-from-accessing-the-task-manager
