### ISSUE TITLE
Dev idea:  "Run after" successful Libki login.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-client#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We have children's software that also tries to usurp (lockout) the Windows Desktop (including suppressing the Libki client.   What we would like to be able to do is automatically run  (program of your choice), but only launch it *after* a successful login. (I.e., like a "Startup Program" to run after Libki has logged in, but not beforehand.  This would be implemented as an entry to the .ini file pointing to the full path of the executable, command, powershell, or batch file to be run.

For many programs (i.e., a browser opening to a library's homepage, or daily announcement or whatever, it can run in the background prior to login, but many educational/kids software have their own independent Windows lockdown features that are incompatible with Libki. (But no reservation functionality)

**Describe alternatives you've considered**
Efforts using Windows Task Scheduler (Remove Libki from Windows client startup programs, and instead create task1=start libki, on trigger=user login), then, upon successful execution of task1, triggers task2.

The reason this hasn't worked so far is that the mere fact of Libki client running, gives Windows or Task Scheduler a definitive way to verify that a (successful) login has occurred.

**Additional context**

**Comment by kylemhall** [comment]
That sounds entirely reasonable to do. I'll take a look and see what I can do!

**Comment by bruzona** [comment]
Great!.  In the meantime is "onlogon.exe" a possible surrogate? (Using Windows Task Scheduler).

I haven't had dependable luck with inactivity timeout feature, but use screensaver activation as a trigger for logout.

  (Windows 10 no longer has the inactivity logout option built in to screensaver options, only lock screen.)

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, Feb 8, 2019 at 12:21 PM -0700, "Kyle M Hall" <notifications@github.com<mailto:notifications@github.com>> wrote:


That sounds entirely reasonable to do. I'll take a look and see what I can do!

**Comment by kylemhall** [comment]
Done! I've added this to our documentation as well: https://github.com/Libki/libki-manual/blob/master/desktop-client.adoc#run-external-program-on-login

**Comment by kylemhall** [comment]
This feature is now available in the latest unstable client download ( https://github.com/Libki/libki-client/releases ) and will be included in the next major release!
