### ISSUE TITLE
SIP configuration (Koha)

### ISSUE THREAD

**Issue by camiloandresrc** [Libki/libki-client#30]
Hello. I'm trying to configure Libki to work with Koha. ¿In which file/location can i find the "location" and "terminator" data for the configuration of the SIP2 protocol? I am using Libki v19.01. Thanks in advance.

**Comment by kylemhall** [comment]
Those are data that you need to get from your ILS. Each ILS will have a different way of implementing a SIP server, so unfortunately we cannot help you find that information :\

If it comes to it, you can just make up a location code, like "LIBRARY" and you can try both terminators CR and CRLF and see if either works for you.
