### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by jamesferrerg** [Libki/libki-client#32]
I would like to change the language to spanish. I find a file in the folder I18N about language. Do I have to modify o create a new file with the language? or already exist?

**Comment by loidor** [comment]
This needs a manual entry point as well, and I need to do some work on the
Swedish translation too.

Same as in the server, I'll get back once I've gotten around to doing it
myself :)

Den tis 30 apr. 2019 kl 21:44 skrev jamesferrerg <notifications@github.com>:

**Comment by loidor** [comment]
Right, here it is!

First is the setup. A .ts file needs to be added to the Libki.pro project file. Here I've added Spanish at the bottom.

```
TRANSLATIONS = languages/libkiclient_fr.ts \
        languages/libkiclient_sv.ts \
        languages/libkiclient_es.ts
```

Next is the creation of the .ts file. This will also update the other language files as well.

```
lupdate Libki.pro
```

Now use Qt Linguist to translate your .ts file.

When that's done, create a .qm file. This will also update the other language files as well.

```
lrelease Libki.pro
```

Finally, add the .qm file to libki.qrc. Here I've added Spanish at the bottom.

```
...
    <qresource prefix="/">
        <file>languages/libkiclient_fr.qm</file>
        <file>languages/libkiclient_sv.qm</file>
        <file>languages/libkiclient_es.qm</file>
    </qresource>
</RCC>
```
