### ISSUE TITLE
Log In as Guest Button

### ISSUE THREAD

**Issue by youngcomputerservices** [Libki/libki-client#35]
In order to minimize staff involvement it would be nice to have a login as guest button on the client that sends a request to the server to auto generate a new one time use guest account.

We have a lot of people who visit our library to use the computers, but either don't bring their library card with them or do not have one. It would be nice if they could just walk up to a computer and login without involving staff to create a guest account.

We often don't have enough computer users in our library at a time that all the stations are filled. I understand for libraries in larger urban centers this could be abused, so it would have to be an option that could be enabled or disabled when installing the client.

**Comment by glump24** [comment]
Why not add a user with the username “guest” and the password “guest” or blank?

**Comment by kylemhall** [comment]
@glump24 that would only work in specific cases. Each account can only be used by one client at a time. You could create a fixed "guest" account for each computer, but it would only be usable for one patron per day unless the renew allotment feature were enabled.
