### ISSUE TITLE
Provide .deb packages and a PPA

### ISSUE THREAD

**Issue by loidor** [Libki/libki-client#58]
I love making things easier for end users. On the Linux side, compiling is a bit of a hassle. So I'm going to have a look at how we can make deb packages and what's needed to provide a PPA this summer.

**Comment by loidor** [comment]
Now there's at least a way to create deb packages for simple installation. From here we can go different ways:
A) set it up with appveyor so it builds automatically just as with the win installer.
B) set up a PPA so it's easy to include in ubuntu (and deriatives) which we chose what versions to put there (i.e. stable)
C) set up an apt repository

A) is great in it being extremely low-maintenance for us.
B) and C) is great in that it updates the clients to the latest stable with apt upgrade.

B) is less work than C) and easier deployment on ubuntu-based distros. That kind of breaks it for other debian based distros though, since PPA is an Ubuntu thing.

C) makes it compatible on all debian-based systems, but is slightly more iffy to setup for the end user compared to B). That also means we'd have to set up and host a repo of our own, which adds even more work.

From this, I scratch C) out of the equation at once, but I think both A) and B) are good things that I'll look more into.

**Comment by loidor** [comment]
@kylemhall Turned out appveyor was quite nice to work with. I set it up so it works with deb packaging naming convention, i.e. `libkiclient_2.2.1-prerelease67_amd64.deb`. 

Would you like something similar with the windows installer?

**Comment by kylemhall** [comment]
@loidor I'm not sure I understand, I'm also using appveyor and it uploads all prelease windows installers to the github releases. If this is not what you mean, let me know!
