### ISSUE TITLE
Special characters not decoded

### ISSUE THREAD

**Issue by fribeiro-keeps** [Libki/libki-client#69]
**Description**
Terms of service text is not decoded.

**To Reproduce**
1. Fill the Terms of service with "João Cação"
2. Login on a client
3. You will see the Terms like "JoÃ£o CaÃ§Ã£o"

**Expected behavior**
You should see "João Cação".

**Comment by kylemhall** [comment]
Closing this issue and moving it to the libki-server repo, as it turns out the problem is on the server side.
