### ISSUE TITLE
Customize client login prefix 

### ISSUE THREAD

**Issue by PPL6265** [Libki/libki-client#73]
Our clients are experiencing difficulty logging in with their barcodes and we’d like to know if it’s possible to have the standard leading digits for our barcode, (i.e. 2308100 ) pre-entered into the form to cut down on the number of digits people need to enter.

Request that we can set a login/barcode prefix would be set in the Libki config file, and then be shown to the left of the card number text box, then the program would add it to the inputted cardnumber *unless* the patron had already done so.

Thanks

**Comment by kylemhall** [comment]
Moved to https://github.com/Libki/libki-server/issues/219
