### ISSUE TITLE
Client Inactivity Warning not working

### ISSUE THREAD

**Issue by PPL1234** [Libki/libki-client#75]
We have set the Client Inactivity Warning at 5 minutes, but after testing on several computers no warning ever appears. (However, we have set our Client Inactivity Logout at 10 minutes and it does log out clients after that amount of time, just with no prior warning.)

**Comment by kylemhall** [comment]
Can you please provide the Operating System version you are using client on?

**Comment by kylemhall** [comment]
Also, what version of the Libki client are you using?

**Comment by PPL1234** [comment]
Windows 10, and Libki version 20.11

**Comment by kylemhall** [comment]
Do you see the warnings for time running out when a patron's time goes under 5 minutes? In Windows 7, it show as a balloon from the system tray. I'm not sure what it would look like in Windows 10.

**Comment by kylemhall** [comment]
<img width="1359" alt="Screen Shot 2021-09-13 at 11 26 45 AM" src="https://user-images.githubusercontent.com/50537/133112563-09ba5d0b-3f76-4573-99ac-930118cec6a1.png">

**Comment by kylemhall** [comment]
It appears to be working for me!

**Comment by PPL1234** [comment]
Unfortunately, I just tested it again and it's still not working. That warning doesn't pop up. I wonder if it's something to do with our settings?
![Libki](https://user-images.githubusercontent.com/90467990/133139382-2e62c0e4-e054-478e-9b13-4c2b5becb6b2.png)

**Comment by kylemhall** [comment]
Those settings look fine to me. I would start by making sure you are using the latest version of the Libki client. You can find it here: https://github.com/Libki/libki-client/releases

If that doesn't help, I would trying installing the client on a fresh install of Windows 10 that has no other third party software installed. It's possible that something you have installed on that computer is suppressing the warning pop-ups.
