### ISSUE TITLE
Computers shutting down when Libki reaches login screen.

### ISSUE THREAD

**Issue by vcyouthlib** [Libki/libki-client#76]
Our 4 public library computers running Libki shut off automatically when they reach the Libki login screen. We have never seen this issue before, and it just started this morning. We have tried restarting the computers several times, to no avail.  To reproduce, start up a computer running Libki. Allow it to reach the login screen. See if it shuts down. Our OS is the latest version of Windows 10.

**Comment by kylemhall** [comment]
So you are saying the Windows PC is running, and as soon as the Libki client starts, the PC goes through the Windows shutdown process?

**Comment by vcyouthlib** [comment]
> So you are saying the Windows PC is running, and as soon as the Libki client starts, the PC goes through the Windows shutdown process?

Yes, that's correct. Our IT is done through our regional library system. They have a theory but so far that's all they have.

**Comment by kylemhall** [comment]
The only thing I can think of is that they are receiving a shutdown message from the server. Check your client statuses and also the Client Shutdown Delay setting and your closing hours.

**Comment by vcyouthlib** [comment]
Thanks, Kyle. My boss solved it. We had closed early the week before, and when she changed our closing hours she accidentally changed the system time as well.

**Comment by kylemhall** [comment]
Thanks for the update!
