### ISSUE TITLE
Is there a complete set of possible commands for the client .ini file

### ISSUE THREAD

**Issue by TypicalLibrarian** [Libki/libki-client#8]
Title says it all. Is there a complete set of possible commands for the LibKi client's .ini file, or are the examples in the installation guide the only ones available? I only ask as I noticed a [Windows] option I did not see noted in the install directions or the example.ini file in the code (from 2015)?

**Comment by kylemhall** [comment]
The example ini should be exhaustive. I don't recall a Windows option so I
think it's safe to say it's deprecated ; )

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )
